In [2]:
import pandas as pd
df=pd.read_csv("tortilla_prices.csv")
df

,State,City,Year,Month,Day,Store type,Price per kilogram
0,Aguascalientes,Aguascalientes,2007,1,10,Mom and Pop Store,9.90
1,Baja California,Mexicali,2007,1,10,Mom and Pop Store,NaN
2,Baja California,Tijuana,2007,1,10,Mom and Pop Store,10.00
3,Baja California Sur,La Paz,2007,1,10,Mom and Pop Store,10.00
4,Campeche,Campeche,2007,1,10,Mom and Pop Store,10.00
...,...,...,...,...,...,...,...
300481,Veracruz,Coatzacoalcos,2025,7,9,Big Retail Store,13.50
300482,Veracruz,Veracruz,2025,7,9,Big Retail Store,13.00
300483,Veracruz,Xalapa,2025,7,9,Big Retail Store,12.83
300484,Yucatán,Mérida,2025,7,9,Big Retail Store,13.17
300485,Zacatecas,Zacatecas,2025,7,9,Big Retail Store,13.50

In [3]:
df.head()

,State,City,Year,Month,Day,Store type,Price per kilogram
0,Aguascalientes,Aguascalientes,2007,1,10,Mom and Pop Store,9.9
1,Baja California,Mexicali,2007,1,10,Mom and Pop Store,NaN
2,Baja California,Tijuana,2007,1,10,Mom and Pop Store,10.0
3,Baja California Sur,La Paz,2007,1,10,Mom and Pop Store,10.0
4,Campeche,Campeche,2007,1,10,Mom and Pop Store,10.0

In [4]:
df.tail()

,State,City,Year,Month,Day,Store type,Price per kilogram
300481,Veracruz,Coatzacoalcos,2025,7,9,Big Retail Store,13.50
300482,Veracruz,Veracruz,2025,7,9,Big Retail Store,13.00
300483,Veracruz,Xalapa,2025,7,9,Big Retail Store,12.83
300484,Yucatán,Mérida,2025,7,9,Big Retail Store,13.17
300485,Zacatecas,Zacatecas,2025,7,9,Big Retail Store,13.50

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300486 entries, 0 to 300485
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   State               300486 non-null  str
 1   City                300486 non-null  str
 2   Year                300486 non-null  int64
 3   Month               300486 non-null  int64
 4   Day                 300486 non-null  int64
 5   Store type          300486 non-null  str
 6   Price per kilogram  294096 non-null  float64
dtypes: float64(1), int64(3), str(3)
memory usage: 16.0 MB

In [6]:
df.shape

(300486, 7)

In [7]:
df.columns

Index(['State', 'City', 'Year', 'Month', 'Day', 'Store type',
       'Price per kilogram'],
      dtype='str')

In [8]:
df["State"].unique()

<StringArray>
[     'Aguascalientes',     'Baja California', 'Baja California Sur',
            'Campeche',            'Coahuila',              'Colima',
             'Chiapas',           'Chihuahua',                'D.F.',
             'Durango',          'Guanajuato',            'Guerrero',
             'Hidalgo',             'Jalisco',         'Edo. México',
           'Michoacán',             'Morelos',             'Nayarit',
          'Nuevo León',              'Oaxaca',              'Puebla',
           'Querétaro',        'Quintana Roo',     'San Luis Potosí',
             'Sinaloa',              'Sonora',             'Tabasco',
          'Tamaulipas',            'Tlaxcala',            'Veracruz',
             'Yucatán',           'Zacatecas']
Length: 32, dtype: str

In [9]:
df["City"].unique()

<StringArray>
[       'Aguascalientes',              'Mexicali',               'Tijuana',
                'La Paz',              'Campeche',        'Piedras Negras',
              'Saltillo',                'Colima',             'Tapachula',
      'Tuxtla Gutiérrez',             'Chihuahua',            'Cd. Juárez',
                  'D.F.',               'ZM D.F.',               'Durango',
         'Gómez Palacio',              'Irapuato',                  'León',
              'Acapulco',          'Chilpancingo',               'Pachuca',
           'Guadalajara',        'ZM Guadalajara',                'Toluca',
               'Morelia',            'Cuernavaca',                 'Tepic',
             'Monterrey',          'ZM Monterrey',                'Oaxaca',
                'Puebla',             'ZM Puebla',             'Querétaro',
                'Cancún',              'Chetumal',       'San Luis Potosí',
              'Culiacán',           'Cd. Obregón',            'Hermosillo',
               'Nogales',          'Villahermosa',          'Cd. Victoria',
             'Matamoros',          'Nuevo Laredo',               'Reynosa',
               'Tampico',              'Tlaxcala',         'Coatzacoalcos',
             'Poza Rica',              'Veracruz',                'Xalapa',
                'Mérida',             'Zacatecas',               'Torreón',
                'Celaya', 'San Luis Río Colorado']
Length: 56, dtype: str

In [10]:
df["Year"].unique()

array([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [11]:
df["Month"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
df["Day"].unique()

array([10, 12, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 29, 30, 31,
        1,  2,  3,  6,  7,  8,  9, 13, 14, 21, 28,  5,  4, 11])

In [13]:
df["Store type"].unique()

<StringArray>
['Mom and Pop Store', 'Big Retail Store']
Length: 2, dtype: str

In [14]:
df["Price per kilogram"].unique()

array([ 9.9 ,   nan, 10.  , ..., 12.55, 16.22, 19.46], shape=(1335,))

In [19]:
df["State"].value_counts()
df["City"].value_counts()
df["Year"].value_counts()
df["Month"].value_counts()
df["Day"].value_counts()
df["Store type"].value_counts()
df["Price per kilogram"].value_counts()

Price per kilogram
14.00    8439
10.00    7930
15.00    6338
16.00    5075
12.00    4937
         ...
25.46       1
17.77       1
17.30       1
27.09       1
20.63       1
Name: count, Length: 1334, dtype: int64

In [20]:
df.describe()

                Year          Month            Day  Price per kilogram
count  300486.000000  300486.000000  300486.000000       294096.000000
mean     2015.748890       6.362513      15.934922           12.615429
std         5.309467       3.418766       8.752586            4.888099
min      2007.000000       1.000000       1.000000            0.000000
25%      2011.000000       3.000000       8.000000            9.700000
50%      2016.000000       6.000000      16.000000           11.500000
75%      2020.000000       9.000000      24.000000           14.500000
max      2025.000000      12.000000      31.000000           31.710000

In [25]:
df2 = df[df["State"]=="Hidalgo"]

In [31]:
df2=df2.rename(columns={"State":"Estado","City":"Ciudad","Year":"Año","Month":"Mes","Day":"Día","Store type":"Tipo de tienda","Price per kilogram":"Precio por kilogramo"})
df2

,Estado,Ciudad,Año,Mes,Día,Tipo de tienda,Precio por kilogramo
20,Hidalgo,Pachuca,2007,1,10,Mom and Pop Store,9.00
73,Hidalgo,Pachuca,2007,1,12,Mom and Pop Store,9.00
126,Hidalgo,Pachuca,2007,1,15,Mom and Pop Store,9.00
179,Hidalgo,Pachuca,2007,1,16,Mom and Pop Store,9.00
232,Hidalgo,Pachuca,2007,1,17,Mom and Pop Store,9.00
...,...,...,...,...,...,...,...
300237,Hidalgo,Pachuca,2025,6,30,Big Retail Store,13.77
300291,Hidalgo,Pachuca,2025,7,2,Big Retail Store,13.77
300345,Hidalgo,Pachuca,2025,7,4,Big Retail Store,13.77
300399,Hidalgo,Pachuca,2025,7,7,Big Retail Store,13.77
300453,Hidalgo,Pachuca,2025,7,9,Big Retail Store,13.77

In [32]:
traductor={
    "Mom and Pop Store":"Tiendita",
    "Big Retail Store2":"Wallmart"
}

In [33]:
df2["Tipo de tienda"]=df2["Tipo de tienda"].replace(traductor)
df2

,Estado,Ciudad,Año,Mes,Día,Tipo de tienda,Precio por kilogramo
20,Hidalgo,Pachuca,2007,1,10,Tiendita,9.00
73,Hidalgo,Pachuca,2007,1,12,Tiendita,9.00
126,Hidalgo,Pachuca,2007,1,15,Tiendita,9.00
179,Hidalgo,Pachuca,2007,1,16,Tiendita,9.00
232,Hidalgo,Pachuca,2007,1,17,Tiendita,9.00
...,...,...,...,...,...,...,...
300237,Hidalgo,Pachuca,2025,6,30,Big Retail Store,13.77
300291,Hidalgo,Pachuca,2025,7,2,Big Retail Store,13.77
300345,Hidalgo,Pachuca,2025,7,4,Big Retail Store,13.77
300399,Hidalgo,Pachuca,2025,7,7,Big Retail Store,13.77
300453,Hidalgo,Pachuca,2025,7,9,Big Retail Store,13.77

In [26]:
df2

,State,City,Year,Month,Day,Store type,Price per kilogram
20,Hidalgo,Pachuca,2007,1,10,Mom and Pop Store,9.00
73,Hidalgo,Pachuca,2007,1,12,Mom and Pop Store,9.00
126,Hidalgo,Pachuca,2007,1,15,Mom and Pop Store,9.00
179,Hidalgo,Pachuca,2007,1,16,Mom and Pop Store,9.00
232,Hidalgo,Pachuca,2007,1,17,Mom and Pop Store,9.00
...,...,...,...,...,...,...,...
300237,Hidalgo,Pachuca,2025,6,30,Big Retail Store,13.77
300291,Hidalgo,Pachuca,2025,7,2,Big Retail Store,13.77
300345,Hidalgo,Pachuca,2025,7,4,Big Retail Store,13.77
300399,Hidalgo,Pachuca,2025,7,7,Big Retail Store,13.77
300453,Hidalgo,Pachuca,2025,7,9,Big Retail Store,13.77